version: "3.5"
services:
  from_mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: from_user
      MYSQL_PASSWORD: from_password
      MYSQL_ROOT_PASSWORD: from_password
      MYSQL_DATABASE: from_db
    volumes:
      - ./data/schema.sql:/docker-entrypoint-initdb.d/01.sql
      - ./data/seed_data.sql:/docker-entrypoint-initdb.d/02.sql

  to_mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: to_user
      MYSQL_PASSWORD: to_password
      MYSQL_ROOT_PASSWORD: to_password
      MYSQL_DATABASE: to_db

networks:
  default:
    name: embulk_test
